### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/reading-ios-debugging#3]
https://learn.co/tracks/mobile-development-with-ios/objective-c-basics/testing-and-debugging/debugging?track_id=6646&batch_id=76

User: ACrystalC

Batch: 000

Current Lesson: Debugging

Location: https://learn.co/tracks/mobile-development-with-ios/objective-c-basics/testing-and-debugging/debugging?track_id=6646&batch_id=76

Bug Description: None of the images in the Debugging lesson for IOS are loading. There are 404 errors when I visit the image links directly.

**Comment by markedwardmurray** [comment]
The images are hosted on github, not Amazon S3. Will fix.

**Comment by adamjonas** [comment]
@markedwardmurray ping. We got another report on this.

**Comment by markedwardmurray** [comment]
Yeah, it’s because Zach hosted the images on Github not on Amazon S3. If the student views it on Github the images display correctly. My rewrite is pending review right now and I republished them on S3.

Thanks!

**Comment by markedwardmurray** [comment]
The rewrite has been deployed and tested in Learn. Images come through.

**Comment by adamjonas** [comment]
:+1:
